### ISSUE TITLE
upcoming cran release of openxlsx

### ISSUE THREAD

**Issue by ycphs** [markheckmann/OpenRepGrid.ic#3]
Hi,

I am the author of the [openxlsx ](https://github.com/ycphs/openxlsx) package. With the new version some of the test in your package fail.

Could you please check the dependencies?

If you have questions please feel free to contact me.

**Comment by markheckmann** [comment]
Hi Philipp,
thanks for pointing that out. However, it seems that it's not `openxlsx` who is the culprit but a breaking change in `shinyFeedback`. I will fix that soon. 
Thanks!
Mark
